# Generated by Django 4.0.5 on 2022-08-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_sku_code_alter_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
