# Generated by Django 4.0.5 on 2022-08-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_entry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
    ]
