# Generated by Django 4.0.5 on 2022-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_entry_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='qty',
        ),
        migrations.AddField(
            model_name='entry',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
