# Generated by Django 4.0.5 on 2022-08-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_entry_qty_entry_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='total_price',
        ),
    ]
