# Generated by Django 4.0.5 on 2022-08-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_entry_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
