# Generated by Django 4.0.5 on 2022-08-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_entry_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sku'),
        ),
    ]
